apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-pvc
  namespace: social-network-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: social-network-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
      - name: file-service
        image: socialworky/worky-file-service-dev:fa330f05f664f3842e003412ee1d0f75570742f9
        ports:
        - containerPort: 3005
        
        # env:
        # - name: NODE_ENV
        #   value: "development"
        
        # - name: APP_PORT
        #   value: "3005"
        
        # - name: REDIS_HOST
        #   value: "social-network-redis-service"
        # - name: REDIS_PORT
        #   value: "6379"

        envFrom:
        - secretRef:
            name: file-service-env-vars
        
        volumeMounts:
        - name: file-storage
          mountPath: /app/uploads
      
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: files-pvc